export const ENGLISH_STRINGS = {
  backUpSwitch: 'Backup to cloud',
  offlineAccess: 'Offline access',
  addNote: 'Add note',
  done: 'Done',
  textIsRequired: 'Text is required',
  textIsTooLong: 'Text must be under 1000 characters',
  writeYourNoteHere: 'Start typing ...',
  prev: 'Prev',
  share: 'Share',
  next: 'Next',
  shareTitle: 'Share this question',
  shareMessage: 'Check out this question: ',
  archive: 'Archive',
};
